steps:
  - name: 'gcr.io/cloud-builders/npm'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Starting build process..."
        npm install --quiet
        echo "Dependencies installed. Running build..."
        ./node_modules/.bin/next build
timeout: '1200s'
options:
  logging: CLOUD_LOGGING_ONLY
